name: CI - Build Test and Reports

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  checks: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java 17 (Azul Zulu)
        uses: actions/checkout@v6
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
      - run: java HelloWorldApp.java

      - name: Build & run tests (Maven)
        working-directory: CiCd Pipelines/recipe-planner-frontend-and-backend/recipe-planner-backend
        run: mvn -B clean verify

      - name: Publish JUnit test report to GitHub Checks
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JUnit Tests
          path: CiCd Pipelines/recipe-planner-frontend-and-backend/recipe-planner-backend/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: false

      - name: Upload Surefire Reports (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: CiCd Pipelines/recipe-planner-frontend-and-backend/recipe-planner-backend/target/surefire-reports

      - name: Upload JaCoCo HTML report (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: CiCd Pipelines/recipe-planner-frontend-and-backend/recipe-planner-backend/target/site/jacoco

  publish-coverage:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download JaCoCo artifact
        uses: actions/download-artifact@v4
        with:
          name: jacoco-report
          path: coverage-site

      - name: Publish JaCoCo site to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.SECRET_TOKEN }}
          publish_dir: coverage-site
          publish_branch: gh-pages

